### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by andyfensham** [emotionLoop/visualCaptcha-frontend-angular#6]
Hi,  I have the same issue with images not showing.  What else should I do to get this working.  Thanks in advance.

My html is :

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
        <link href="bower_components/visualcaptcha.angular/visualcaptcha.css" rel="stylesheet" />
    </head>
    <body ng-app="app" ng-controller="captchaController">
        <div captcha options="captchaOptions"></div>

        <script data-require="angular.js@1.3.x"         src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.js" data-semver="1.3.8"></script>
        <script src="bower_components/visualcaptcha.angular/visualcaptcha.angular.js"></script>
        <script src="app/visualcaptchatest.js"></script>
    </body>
    </html>

and my javascript file is :

    angular.module( 'app', [ 'visualCaptcha' ] )
        .controller( 'captchaController', function( $scope ) {
            $scope.captchaOptions = {
                imgPath: '/bower_components/visualcaptcha.angular/img/',
                captcha: { numberOfImages: 5 },
                // use init callback to get captcha object
                init: function ( captcha ) {
                    $scope.captcha = captcha;
                }
            };
        } );

**Comment by BrunoBernardino** [comment]
Can you show me the requests made when accessing? What's the URL it's trying to get for the images (not the accessibility ones, but the ones for the options)?

**Comment by mandekisd** [comment]
Hi,

I have the same issue.

The imageUrl() function returns: http://localhost:9000/#/images/captcha/undefined?r=ja7w8xedwd0zr529

I guess that it is missing the image name.  Do we have to define it or not?  If yes how?

Thanks

**Comment by BrunoBernardino** [comment]
It should've been fetched on the first request to the back-end. What was the result of that one (the `/start/*` one)?

**Comment by mandekisd** [comment]
Don't see any request at all.  The url posted was extracted after setting a breakpoint.  Could there be an issue with the "request" function?

**Comment by BrunoBernardino** [comment]
Looking at the web inspector (network tab) there are no requests? visualCaptcha makes a starting one to `/start/*` with `*` being the number of images requested.

**Comment by BrunoBernardino** [comment]
If there's no request, visualCaptcha's not being defined/called properly. Can you share some code?

**Comment by mandekisd** [comment]
I followed the instructions.  Give me couple of minutes and I will post the code here.

**Comment by mandekisd** [comment]
In the controller:
//Captcha
        $scope.captchaOptions = {
            imgPath: 'images/captcha/',
            captcha: {numberOfImages: 5},
            // use init callback to get captcha object
            init   : function (captcha) {
                $scope.captcha = captcha;
            }
        };
        //End captcha

HTML:
<div class="form-group">
       <div captcha options="captchaOptions"></div>
 </div>

The refresh and accessibility images are loaded.  Not the others.

In the network panel I see only the requests for refresh and accessibility:

Remote Address:127.0.0.1:9000
Request URL:http://localhost:9000/images/captcha/refresh.png
Request Method:GET
Status Code:304 Not Modified

Remote Address:127.0.0.1:9000
Request URL:http://localhost:9000/images/captcha/accessibility.png
Request Method:GET
Status Code:304 Not Modified

No requests for /start/* or anything like it.

**Comment by BrunoBernardino** [comment]
There are no errors in the console? You've toggled to watch the XHR requests, right?

Going at http://ruby.demo.visualcaptcha.net/ the front-end sample is angular (you can see the code at https://github.com/emotionLoop/visualCaptcha-ruby, specifically [HTML](https://github.com/emotionLoop/visualCaptcha-ruby/blob/master/public/index.html) and [JS](https://github.com/emotionLoop/visualCaptcha-ruby/blob/master/public/js/main.js))

This is the request I'm getting there, that you need to see (even if it's pending or an error):

![screen shot 2015-04-15 at 12 15 48](https://cloud.githubusercontent.com/assets/1239616/7157653/717d0916-e369-11e4-9343-a320204250fa.png)

**Comment by mandekisd** [comment]
I can see the ```/start/*``` request in the above example but not in mine.  Not sure what may be wrong.  Anything else to try?

**Comment by BrunoBernardino** [comment]
Have you compared your HTML and JS to what's in the samples above?

**Comment by mandekisd** [comment]
Yes and it looks the same.  I don't understand why the requests to the refresh and accessibility are made but not for the start.

**Comment by BrunoBernardino** [comment]
Those just mean that angular is rendering them, thus the browser requests them.

Not requesting the `start` endpoint, though, means something is off. What is the URL for the backend part of visualCaptcha? Can you get anything by going there directly?

Is there a URL I can look at?

**Comment by mandekisd** [comment]
Sorry no URL for you to look directly.  I am developing locally.  So you suggest that I should try to "see" the images in a URL like: http://localhost:9000/start/* ?

**Comment by mandekisd** [comment]
I managed to have my backend replying to: http://localhost:9000/start/0.png and returning the image.

Still no request originating from the captcha.

**Comment by BrunoBernardino** [comment]
We need to do this over screen sharing or pair programming then.

When does it work for you today or tomorrow? I can do today after 7pm GMT, if not too late, or tomorrow same time.

**Comment by mandekisd** [comment]
I am GMT+1 so it sounds good for me today.  When u are ready send me an email.  Thanks.

**Comment by mandekisd** [comment]
[SOLVED]
Solution:  Add the url parameter to the captcha options as such,

Before:

```
angular
    .module( 'app', [ 'visualCaptcha' ] )
    .controller( 'captchaController', function( $scope ) {
        $scope.captchaOptions = {
            imgPath: 'img/',
            captcha: { numberOfImages: 5 },
            // use init callback to get captcha object
            init: function ( captcha ) {
                $scope.captcha = captcha;
            }
        };
    } );
```

After:

```
angular
    .module( 'app', [ 'visualCaptcha' ] )
    .controller( 'captchaController', function( $scope ) {
        $scope.captchaOptions = {
            imgPath: 'img/',
            captcha: { numberOfImages: 5, url: '<path_to_your_back_end_base_url_plus_port>' },
            // use init callback to get captcha object
            init: function ( captcha ) {
                $scope.captcha = captcha;
            }
        };
    } );
```

**Comment by JoGe92** [comment]
![captura de pantalla 2015-07-23 a la s 16 33 25](https://cloud.githubusercontent.com/assets/7005582/8862746/949ca694-3158-11e5-8197-3332cfb01f43.png)

hi, im trying to run the demo and  i get this response from de XHR request, is like it doesn`t find where to make the request or idk, what can i do?

**Comment by mandekisd** [comment]
Did you try to pass as a parameter the backend url as above?

captcha: { numberOfImages: 5, **url: '<path_to_your_back_end_base_url_plus_port>' **},

**Comment by BrunoBernardino** [comment]
It seems you're using the [PHP/jQuery demo](https://github.com/emotionLoop/visualCaptcha-PHP). Let me know if I'm wrong.

The URL you're pointing to is wrong. Please look at https://github.com/emotionLoop/visualCaptcha-PHP#run-server

If you start the server with `$ php -S localhost:8282 -t public` you should be going to `http://localhost:8282`.
