### ISSUE TITLE
How to show 2 captcha's on the same page 

### ISSUE THREAD

**Issue by heywei** [emotionLoop/visualCaptcha-frontend-angular#9]
Hi .

I have one html page and one angular javascript . it works fine with only 1 captcha on the page. But I need to implement 2 captcha's on the same page. They can be the same captcha content or different. 

The reason to have 2 captcha is that the user 'signup' and 'login' parts are both on this html page. 

I started with the approach to have the 'same' captcha show twice on the page with below approach.

### angularjs
```js
$scope.captchaOptions = {
    imgPath: 'img/',
    captcha: {
        numberOfImages: 5,
        url: '/api/captcha',
        callbacks: 
        {
    	    loading: function( captcha ){
    	        console.log( 'I am loading.', captcha );
    	    },
    	    loaded: function( captcha ){
                console.log( 'I am loaded.', captcha );
            }
        }
    },
    init: function ( captcha ) {
        $scope.captcha = captcha;
        $scope.captcha1 = captcha;
    }
};
```

### html
```html
<div captcha1 options="captchaOptions"></div>   
<div captcha options="captchaOptions"></div>
``` 

The result is that the "div captcha " part  is shown, but the "div captcha1" part  is not shown.  

Wonder how to have 2 captchas(same or different) on the same page?  

Thank you.

**Comment by BrunoBernardino** [comment]
Hi @heywei ! 

Thanks for using visualCaptcha!

We have an example for 2 independent captchas (you'll need to use the `data-namespace` attribute) in [this github repo](https://github.com/emotionLoop/visualCaptcha-multiple).

[Here's the HTML for it](https://github.com/emotionLoop/visualCaptcha-multiple/blob/master/app/views/demo.php#L42-L68).

That demo's in jQuery, but should work for you as well.

Let me know if that works!

**Comment by heywei** [comment]
Hi Bruno,

Many thanks for helping out.  I also found this [note ](https://github.com/emotionLoop/visualCaptcha-frontend-core#initialization-of-multiple-captchas-on-the-same-page) about multiple captchas. 

I have tried the below way. 

Javascript
-----------------------------------------
    $scope.signupcaptchaOptions = {
            imgPath: 'img/',
            captcha: {
                numberOfImages: 5,
                namespaceFieldName: 'myFieldName',
                url: '/api/captcha',
                callbacks: 
                {
    	            loading: function( captcha ){
    	                console.log( 'I am loading.', captcha );
    	            },
    	            loaded: function( captcha ){
    	                console.log( 'I am loaded.', captcha );
    	            }
                }
            },
            init: function ( captcha ) {
                $scope.captcha = captcha;
            }
        };
    
    $scope.logincaptchaOptions = {
            imgPath: 'img/',
            captcha: {
                numberOfImages: 5,
                namespaceFieldName: 'myFieldName',
                url: '/api/captcha',
                callbacks: 
                {
    	            loading: function( captcha ){
    	                console.log( 'I am loading.', captcha );
    	            },
    	            loaded: function( captcha ){
    	                console.log( 'I am loaded.', captcha );
    	            }
                }
            },
            init: function ( captcha ) {
                $scope.captcha = captcha;
            }
        };

Html
-----------------------------------------------

`<div captcha options="signupcaptchaOptions"  data-namespace="signup"></div>    <div captcha options="logincaptchaOptions"  data-namespace="login"></div>`  


After the implementation, I can see both captchas shown on my page with different contents, which is quite good.    However every time when i call "$scope.captcha.refresh();"   or "$scope.captcha.getCaptchaData().valid" , it is always the 2nd captcha (data-namespace="login") is used/selected. 

I am quite new to the java frontend tech,   Wonder if there is anything I should do differently? 

Thanks!

**Comment by heywei** [comment]
Hi Bruno,

I actually did more testing and made some progress. I think I get it to work now:)

javascript:
--------------------------------------
    $scope.signupcaptchaOptions = {
            imgPath: 'img/',
            captcha: {
                numberOfImages: 5,
                url: '/api/captcha',
                callbacks: 
                {
    	            loading: function( captcha ){
    	                console.log( 'I am loading.', captcha );
    	            },
    	            loaded: function( captcha ){
    	                console.log( 'I am loaded.', captcha );
    	            }
                }
            },
            init: function ( captcha ) {
                $scope.signupcaptcha = captcha;
            }
        };
    
    $scope.logincaptchaOptions = {
            imgPath: 'img/',
            captcha: {
                numberOfImages: 5,
                url: '/api/captcha',
                callbacks: 
                {
    	            loading: function( captcha ){
    	                console.log( 'I am loading.', captcha );
    	            },
    	            loaded: function( captcha ){
    	                console.log( 'I am loaded.', captcha );
    	            }
                }
            },
            init: function ( captcha ) {
                $scope.logincaptcha = captcha;
            }
        };
        

Html
----------------------------------
`<div captcha options="signupcaptchaOptions"  data-namespace="signup"></div>  <div captcha options="logincaptchaOptions"  data-namespace="login"></div> `

Now I am able to use $scope.signupcaptcha.refresh(); or  $scope.logincaptcha.refresh(); to control each captcha.

**Comment by BrunoBernardino** [comment]
Awesome news @heywei !

Would you say this issue is closed now?

**Comment by heywei** [comment]
Thank you@BrunoBernardino, Yes please close this issue.
